#!/usr/bin/env python3
"""
Parse DELIL_tek_dosya_birlestirilmis_icerik_paketi.json
Skip existing DELIL-001..DELIL-117 cards.
Output Dart const entries for the 276 new cards.
"""

import json, re, sys

JSON_PATH = r"C:\Users\AG\Documents\Downloads\urasokul\DELIL_tek_dosya_birlestirilmis_icerik_paketi.json"
OUT_PATH  = r"C:\src\delil\tools\new_cards_generated.dart"

# ── Existing IDs to skip ────────────────────────────────────────────────────
EXISTING = {f"DELIL-{i:03d}" for i in range(1, 118)}

# ── Category mapping ────────────────────────────────────────────────────────
# JSON category string → Dart const variable name
CAT_MAP = {
    "Felsefi ve Kelâmî Deliller":                      "_felsefe",
    "Bilimsel ve Doğa Üzerinden Deliller":             "_bilim",
    "İman Hakikatleri ve Risale-i Nur Tarzı Deliller": "_risale",
    "Fıtrat, Ahlak ve İnsan Delilleri":                "_fitrat",
    "İtirazlar ve Cevap Kartları":                     "_itiraz",
    "Kâinat ve Günlük Hayat Delilleri":                "_kainat",
    # ── New categories ──────────────────────────────────────────────────
    "Matematiksel ve Mantıksal Deliller":              "_matematik",
    "Biyolojik Deliller":                              "_biyoloji",
    "Fizik ve Kozmoloji Delilleri":                    "_fizik",
    "Astronomi Delilleri":                             "_astronomi",
    "Estetik ve Anlam Delilleri":                      "_estetik",
    "Tarihî Deliller":                                 "_tarih",
    "Tarihî ve Felsefi Deliller":                      "_tarih",
    "Tarihî Filozoflar ve Klasik Savlar":              "_tarih",
    "Matematiksel, Mantıksal ve İstatistiksel Deliller": "_matematik",
    "Biyolojik ve Canlılık Delilleri":                 "_biyoloji",
    "Fizik, Kozmoloji ve Kimya Delilleri":             "_fizik",
    "İslami, Rivayet ve Manevi Delil Kartları":        "_risale",
    "Bilinç, Ahlak ve İnsan Delilleri":                "_fitrat",
    # mapped to existing
    "Bilinç ve Zihin Delilleri":                       "_felsefe",
    "Ahlak Delilleri":                                 "_fitrat",
    "Fıtrat Delilleri":                                "_fitrat",
    "Felsefi ve Psikolojik Deliller":                  "_fitrat",
    "Felsefi Deliller":                                "_felsefe",
    "Bilişim ve Bilgi Teorisi":                        "_bilim",
}

def esc(s):
    """Escape string for Dart single-quoted string."""
    if s is None:
        return ""
    s = str(s)
    s = s.replace("\\", "\\\\")
    s = s.replace("'", "\\'")
    return s

def strength_map(s):
    mapping = {
        "yüksek": "yüksek",
        "orta-yüksek": "orta-yüksek",
        "orta": "orta",
        "düşük": "orta",
    }
    return mapping.get(str(s).lower(), "orta")

with open(JSON_PATH, encoding="utf-8") as f:
    data = json.load(f)

cards = data["cards"]
new_cards = [c for c in cards if c["id"] not in EXISTING]
print(f"Total cards in JSON : {len(cards)}")
print(f"Existing (skipped)  : {len(EXISTING)}")
print(f"New cards to add    : {len(new_cards)}")

# ── Group by mapped category ────────────────────────────────────────────────
from collections import defaultdict
by_cat = defaultdict(list)
unknown_cats = set()
for c in new_cards:
    raw_cat = c.get("category", "")
    dart_cat = CAT_MAP.get(raw_cat)
    if dart_cat is None:
        unknown_cats.add(raw_cat)
        dart_cat = "_felsefe"   # fallback
    by_cat[dart_cat].append((c, dart_cat))

if unknown_cats:
    print(f"WARNING – unmapped categories: {unknown_cats}")

# ── Dart const name → display string ────────────────────────────────────────
CAT_DISPLAY = {
    "_felsefe":  "Felsefi ve Kelâmî Deliller",
    "_bilim":    "Bilimsel ve Doğa Üzerinden Deliller",
    "_risale":   "İman Hakikatleri ve Risale-i Nur Tarzı Deliller",
    "_fitrat":   "Fıtrat, Ahlak ve İnsan Delilleri",
    "_itiraz":   "İtirazlar ve Cevap Kartları",
    "_kainat":   "Kâinat ve Günlük Hayat Delilleri",
    "_matematik":"Matematiksel ve Mantıksal Deliller",
    "_biyoloji": "Biyolojik Deliller",
    "_fizik":    "Fizik ve Kozmoloji Delilleri",
    "_astronomi":"Astronomi Delilleri",
    "_estetik":  "Estetik ve Anlam Delilleri",
    "_tarih":    "Tarihî Deliller",
}

# Friendly cat order for output
CAT_ORDER = [
    "_matematik", "_biyoloji", "_fizik", "_astronomi",
    "_estetik", "_tarih",
    "_felsefe", "_bilim", "_fitrat", "_risale", "_itiraz", "_kainat",
]

lines = []
lines.append("// AUTO-GENERATED by gen_cards.py — DO NOT EDIT MANUALLY")
lines.append("// Paste these Delil(...) entries into allDeliller list in delil_data.dart")
lines.append("")

total_written = 0
for dart_cat in CAT_ORDER:
    group = by_cat.get(dart_cat, [])
    if not group:
        continue
    display = CAT_DISPLAY[dart_cat]
    lines.append(f"  // ─────────────── {display.upper()} ───────────────")
    lines.append("")
    for (c, _) in group:
        card_id   = esc(c.get("id", ""))
        subcat    = esc(c.get("subcategory", ""))
        title     = esc(c.get("title", ""))
        short     = esc(c.get("short", ""))
        expanded  = esc(c.get("expanded", ""))
        strength  = strength_map(c.get("strength", "orta"))
        objection = esc(c.get("objection", ""))
        reply     = esc(c.get("reply", ""))
        sources   = c.get("sources", [])
        tags      = c.get("tags", [])

        tag_str  = ", ".join(f"'{esc(t)}'" for t in tags)
        src_str  = ", ".join(f"'{esc(s)}'" for s in sources)

        obj_line = f"\n    objection: '{objection}'," if objection else ""
        rep_line = f"\n    reply: '{reply}'," if reply else ""

        lines.append(f"  Delil(")
        lines.append(f"    id: '{card_id}', category: {dart_cat}, subcategory: '{subcat}',")
        lines.append(f"    title: '{title}',")
        lines.append(f"    short: '{short}',")
        lines.append(f"    expanded: '{expanded}',")
        lines.append(f"    tags: [{tag_str}],")
        lines.append(f"    strength: '{strength}',")
        if src_str:
            lines.append(f"    sources: [{src_str}],")
        if objection:
            lines.append(f"    objection: '{objection}',")
        if reply:
            lines.append(f"    reply: '{reply}',")
        lines.append(f"  ),")
        lines.append("")
        total_written += 1

out = "\n".join(lines)
with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write(out)

print(f"Written {total_written} card entries to {OUT_PATH}")

# ── Also print new category counts ──────────────────────────────────────────
print("\nCards per new category:")
for dart_cat in CAT_ORDER:
    group = by_cat.get(dart_cat, [])
    if group:
        print(f"  {CAT_DISPLAY[dart_cat]:50s}  {len(group)}")
